### ISSUE TITLE
Offline tab

### ISSUE THREAD

**Issue by Qwash** [Emano-Waldeck/work-offline#2]
It would be very useful to reject connections for selected tab only

**Comment by Emano-Waldeck** [comment]
We have this feature in version 0.1.2. Use the right-click context menu item on page action to make just a single tab go to the offline mode.

**Comment by Qwash** [comment]
When the content you need is ready in a tab but it still downloading unnecessary resources I need a way to terminating this tab connections without affecting other tabs, this is the main reason for requesting the "offline tab" feature, but currently if you switched a tab offline while it still downloading resources the extension redirect you to the "Offline mode" page
Can you please add an option to stop this redirect, this should happens only when you try to navigate to a new URL
